# CI on github actionn
name: Build project

on:
  push:
    paths-ignore:
      - '*.md'
    branches:
    - master

jobs:
  build_job:
    name: build
    runs-on: [macos-latest]
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        
      - name: setup node version 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: cache
        uses: actions/cache@v2.1.0
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            **/node_modules
          # An explicit key for restoring and saving the cache
          key: ${{hashFiles('**/package-lock.json')}}_build_${{runner.os}}
          # An ordered list of keys to use for restoring the cache if no cache hit occurred for key!
          # restore-keys: <optional>

      - name: install package
        run: npm install
        
      - name: build
        run: npm run build
      
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2
        with:
          name: distributes
          path: build

      - name: ls build
        run: ls -al build
        
  publish_job:
    name: publish
    runs-on: [macos-latest]
    needs: [build_job]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: distributes
          path: build
        
      - name: copy to s3
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://modooteam-travis

    
