# slack push messageeeeeee!~!!~~!!~
name: Slack test

on:
  push:
    branches: [ slack ]

jobs:
  messaging:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
     #- run: npm die
     - uses: act10ns/slack@v1
       with: 
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
       if: always()
