name: Trigger test

on:
  push:
    branches:
    - test

jobs:
  test_job_A:
    name: set_env
    runs-on: [ubuntu-latest]
    env: 
      foo: 'bar'
    steps:
      - name: test
        run: | 
          echo 'done';
          
  test_job_B:
    name: print_env
    runs-on: [ubuntu-latest]
    steps:
      - name: pring env
        run: |
          echo foo is ${{ env.foo }}
    
