name: Trigger test
env: 
  isFoo: ${{ github.ref == 'refs/heads/test' && 'Y' || 'N' }}
on:
  push:
    branches:
    - test

jobs:
  test_job_A:
    name: set_env
    runs-on: [ubuntu-latest]
    env: 
      foo: 'bar'
    steps:
      - name: test
        run: | 
          echo 'done';
          
  test_job_B:
    name: print_env
    runs-on: [ubuntu-latest]
    env: 
      foo2: 'bar2'
    steps:
      - name: pring env
        run: |
          echo foo is ${{ env.foo }}
          echo foo2 is ${{ env.foo2 }}
          echo isFoo is ${{ env.isFoo }}
    
