name: Trigger test

on:
  push:
    branches:
    - test

jobs:
  test_job:
    name: test_job
    runs-on: [ubuntu-latest]

    steps:
      - name: test
        env:
          foo: 'bar'
        run: |
          echo |
            'it works.'
